routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/siengaja', function(){
    return "iseng aja";
});

// Route::get('/artikel', 'ArticleController@index')->name('article.index');

Route::resource('/artikel', 'ArticleController')->middleware('auth');

Route::resource('/author', 'AuthorController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class article extends Model
{
    public function author(){
        return $this->belongsTo('App\Author', 'id_author', 'id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dd(Auth::user());
        $data['articles'] = article::all();
        // dd($article);
        $data['title'] = "This Is Sparta";
        return view('articles.index', $data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $newArticle = new Article();
        $newArticle->judul=$request->judul;
        $newArticle->konten=$request->konten;
        $newArticle->tanggal=$request->tanggal;
        $newArticle->id_author=$request->id_author;
        $file       = $request->file('file');
        $fileName   = $file->getClientOriginalName();
        $request->file('file')->move("image/", $fileName);

        $newArticle->file = $fileName;
        $newArticle->save();

        return redirect()->route('artikel.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\article  $article
     * @return \Illuminate\Http\Response
     */
    public function show($article_id)
    {
        $data['article'] = article::find($article_id);
        return view('articles.home', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit($article_id)
    {
        $data['article'] = article::find($article_id);
        return view('articles.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $article_id)
    {
        $article= article::find($article_id);
        $article->judul = $request->judul;
        $article->konten = $request->konten;
        $article->tanggal = $request->tanggal;
        $article->id_author=$request->id_author;
        if($request->file('file') == "")
        {
            $article->file = $article->file;
        } 
        else
        {
            $file       = $request->file('file');
            $fileName   = $file->getClientOriginalName();
            $request->file('file')->move("image/", $fileName);

            $article->file = $fileName;
        }
        $article->save();
        return redirect()->route("artikel.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy($article_id)
    {
        // dd($article_id);
        $article= article::find($article_id);
        $article->delete();
        return redirect()->route("artikel.index");
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['authors'] = Author::all();
        return view('authors.tampilauthor', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('authors.inputauthor');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newAuthor = new Author();
        $newAuthor->nama=$request->nama;
        $newAuthor->email=$request->email;
        $newAuthor->password=$request->password;
        $newAuthor->no_hp=$request->no_hp;
        $newAuthor->alamat=$request->alamat;
        $newAuthor->perusahaan=$request->perusahaan;
        $newAuthor->alamat_perusahaan=$request->alamat_perusahaan;
        $newAuthor->save();

        return redirect()->route('author.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function show(Author $author)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function edit($author_id)
    {
        $data['author'] = Author::find($author_id);
        return view('authors.inputauthor', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $author_id)
    {
        $author= Author::find($author_id);
        $author->nama = $request->nama;
        $author->email = $request->email;
        $author->password = $request->password;
        $author->no_hp = $request->no_hp;
        $author->alamat = $request->alamat;
        $author->perusahaan = $request->perusahaan;
        $author->alamat_perusahaan = $request->alamat_perusahaan;
        $author->save();
        return redirect()->route("author.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function destroy($author_id)
    {
        $author= Author::find($author_id);
        $author->delete();
        return redirect()->route("author.index");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/articles/form.blade.php
@extends('layouts');
@section('content')

    @if(@!$article)
    <form method="POST" action="{{route('artikel.store')}}" enctype="multipart/form-data">
    @method('POST')
    @else
    <form method="POST" action="{{route('artikel.update', ['articles'=>$article->id])}}"enctype="multipart/form-data">
    @method('PUT')
    @endif

    @csrf
    <div class="form-group">
        <label for="exampleInputEmail1">Judul Artikel</label>
        <input type="text" class="form-control" id="name"  placeholder="Enter Judul" name="judul" value="{{@$article->judul}}">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Artikel</label>
        <textarea name="konten" class="form-control" id="konten" placeholder="Masukan Artikel" value="{{@$article->konten}}" cols="30" rows="10">{{@$article->konten}}</textarea>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Tanggal Publish</label>
        <input type="date" class="form-control" id="password" placeholder="Masukan Tanggal Unggah" name="tanggal" value="{{@$article->tanggal}}">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Author</label>
        <input type="text" class="form-control" id="id_author" placeholder="Masukan id author" name="id_author" value="{{@$article->id_author}}">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Masukan gambar</label>
        <input type="file" class="form-control" id="file" placeholder="Masukan Gambar" name="file" value="{{@$article->file}}">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/articles/home.blade.php
@extends('layouts')
@section('content')
    <div class="card" style="width: auto;">
    <div class="card-body" style="width: auto;">
        <h5 class="card-title">{{$article->judul}}</h5>
        <img class="card" src="{{asset('../public/image/'.$article->file)}}" style="height:300px; margin:center">
        <p class="card-text">{{$article->konten}}</p>
        <p><h6 style="text-align:right">Ditulis Oleh {{ $article->author->nama }}<h6></p>
        <a href="{{route('artikel.index')}}" class="btn btn-primary">Kembali</a>
    </div>
    </div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts');
@section('content')

<table class="table">
@foreach ($articles as $article)
        <div class="card" style="width: auto;">
        <div class="card-body" style="width: auto;">
        <h5 class="card-title">{{$article->judul}}</h5>
        <img class="card" src="../public/image/{{$article->file}}" style="height:300px">
        <h6 class="card-title">{{$article->tanggal}}</h6>
        <p class="card-text">{{substr($article->konten, 0, 400)}} {{strlen($article->konten)>10? '...':''}}</p>
        <a href="{{route('artikel.show', ['artikel'=>$article->id])}}" class="btn btn-primary">See More</a>
        <a href="{{route('artikel.edit', ['artikel'=>$article->id])}}" class="btn btn-primary">Edit</a>
        <form action="{{route('artikel.destroy', ['artikel'=>$article->id])}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>
    </div>
@endforeach
    </thead>
</table>
<a href="{{route('artikel.create')}}" class="btn btn-success">Create New Articles</a>
@endsection

resources/views/authors/inputauthor.blade.php
@extends('layouts');
@section('content')

@if(@!$author)
<form method="POST" action="{{route('author.store')}}">
@method('POST')
@else
<form method="POST" action="{{route('author.update', ['authors'=>$author->id])}}">
@method('PUT')
@endif
@csrf
  <div class="form-group">
    <label for="exampleInputEmail1">Nama</label>
    <input type="text" class="form-control" id="nama" placeholder="Enter Nama" name="nama" value="{{@$author->nama}}">
  </div> 
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="email" placeholder="Enter email" name="email" value="{{@$author->email}}">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password" name="password" value="{{@$author->password}}">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Nomor Telepon/HP</label>
    <input type="text" class="form-control" id="no_hp" placeholder="Enter Nomor" name="no_hp" value="{{@$author->no_hp}}">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Alamat</label>
    <input type="text" class="form-control" id="alamat" placeholder="Enter Alamat" name="alamat" value="{{@$author->alamat}}">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Perusahaan</label>
    <input type="text" class="form-control" id="perusahaan" placeholder="Masukan Perusahaan Anda" name="perusahaan" value="{{@$author->perusahaan}}">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Alamat Perusahaan</label>
    <input type="text" class="form-control" id="alamat_perusahaan" placeholder="Enter Alamat Perusahaan" name="alamat_perusahaan" value="{{@$author->alamat_perusahaan}}">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/authors/login.blade.php
@extends('layouts');
@section('content')
    <form method="POST" action="">
    @csrf
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/authors/tampilauthor.blade.php
@extends('layouts');
@section('content')

<table class="table">
    <thead>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>E-mail</th>
            <th>Nomor HP</th>
            <th>Alamat</th>
            <th>Perusahaan</th>
            <th>Alamat Perusahaan</th>
        </tr>
@foreach ($authors as $author)
        <tr>
            <th>{{$author->id}}</th>
            <th>{{$author->nama}}</th>
            <th>{{$author->email}}</th>
            <th>{{$author->no_hp}}</th>
            <th>{{$author->alamat}}</th>
            <th>{{$author->perusahaan}}</th>
            <th>{{$author->alamat_perusahaan}}</th>
            <th><a href="{{route('author.edit', ['author'=>$author->id])}}">Edit</a>
                <form action="{{route('author.destroy', ['author'=>$author->id])}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit">Delete</button>
                </form>
            </th>
        </tr>
@endforeach
    </thead>
</table>
<a href="{{route('author.create')}}">Create New Author</a>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
           
        @include('navbar')

        @yield('content')
    
    </div>    
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{route('artikel.index')}}">Artikel <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{route('author.index')}}">Author</a>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>